name: 'Hello action'
description: 'Echo a greeting message'
inputs:
  name:
    description: 'Name to greet'
    required:  true
runs:
  using: 'composite'
  steps:
    - run: echo "${{ inputs.name }}"
      shell:  bash

